name: "Thread Safety Tests"

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  thread-safety:
    name: "Thread Safety"
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
          - "lts"
          - "pre"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Julia ${{ matrix.version }}"
        uses: julia-actions/setup-julia@v2
        with:
          version: "${{ matrix.version }}"

      - name: "Cache Julia packages"
        uses: julia-actions/cache@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1

      - name: "Run thread safety tests (4 threads)"
        run: |
          julia --threads=4 --code-coverage=user --check-bounds=yes --compiled-modules=yes \
                --project=@. --color=yes -e '
            using Pkg
            Pkg.test()
          '
        env:
          GROUP: ThreadSafety

      - name: "Process Coverage"
        uses: julia-actions/julia-processcoverage@v1

      - name: "Report Coverage"
        uses: codecov/codecov-action@v5
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          files: lcov.info
          token: "${{ secrets.CODECOV_TOKEN }}"
          fail_ci_if_error: false
